// Import verified BB identities and artwork from the Haven Wiki checkout.
// Run: node tools/sync_wiki_catalog.cjs /path/to/ephinea4haven.github.io
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const wiki = process.argv[2];
if (!wiki) throw new Error('Pass the Haven Wiki checkout path');
const read = file => JSON.parse(fs.readFileSync(file, 'utf8'));
const catalog = read(path.join(wiki, 'src/app/generated/monster-catalog/index.json'));
const details = read(path.join(wiki, 'src/app/generated/monster-catalog/details.server.json'));
const images = read(path.join(wiki, 'content/monster-catalog/images.json'));
const authority = read(path.join(root, 'i18n_names.json')).monsters;
const context = {window: {}};
vm.runInNewContext(fs.readFileSync(path.join(root, 'bb/data/en.js'), 'utf8'), context);
const profiles = {};
const assets = new Map();
function variant(monster, ultimate) {
  const name = (ultimate ? monster.ultimateNames : monster.names).en.replace(/ \([^)]*\)/g, '');
  const key = Object.keys(authority).find(key => key.toLowerCase() === name.toLowerCase());
  if (!key) throw new Error(`Missing monster translation: ${name}`);
  const image = ultimate ? monster.ultimateImage : monster.image;
  const source = image && Object.values(images).find(value => value.path === image);
  if (image && !source) throw new Error(`Missing image provenance: ${image}`);
  if (image) assets.set(path.basename(image), path.join(wiki, image.slice(1)));
  const ja = authority[key].ja || (ultimate ? monster.ultimateNames : monster.names).ja.replace(/ \([^)]*\)/g, '');
  if (!ja || !authority[key].zh) throw new Error('Missing translation: ' + name);
  return {names: {en: key, zh: authority[key].zh, ja}, image: image ? path.basename(image) : null,
    source: source?.page || null};
}
for (const [difficulty, data] of Object.entries(context.window.DROP_DATA_EN.data)) {
  for (const [episode, rows] of Object.entries(data.monsters)) {
    const group = profiles[episode] ||= {};
    for (const row of rows) {
      if (group[row.name]) continue;
      const diff = {Normal: 'n', Hard: 'h', 'Very Hard': 'vh', Ultimate: 'u'}[difficulty];
      const monster = catalog.find(m => `Episode ${m.episode}` === episode && details[m.id].drops[diff]?.name === row.name);
      if (!monster) throw new Error(`Unmapped monster: ${episode} / ${row.name}`);
      group[row.name] = {id: monster.id, normal: variant(monster, false), ultimate: variant(monster, true)};
    }
  }
}
const itemCatalog = new Map(read(path.join(wiki, 'src/app/generated/item-catalog/index.json')).map(row => [row[1], row[0]]));
const items = {};
for (const data of Object.values(context.window.DROP_DATA_EN.data)) for (const groups of Object.values(data)) {
  for (const rows of Object.values(groups)) for (const row of rows) for (const cell of row.drops) {
    for (const drop of cell.items || [cell]) {
      if (!drop.item) continue;
      const id = itemCatalog.get(drop.item);
      if (!id) throw new Error('Missing item detail: ' + drop.item);
      items[drop.item] = id;
    }
  }
}
// Finish validation, including reading every source image, before changing any
// published files. Keep old artwork until the new manifest has been installed.
const artwork = new Map([...assets].map(([filename, source]) => [filename, fs.readFileSync(source)]));
const manifest = '// Generated by tools/sync_wiki_catalog.cjs; image sources are recorded per variant.\nwindow.BB_MONSTERS = ' + JSON.stringify(profiles, null, 2) + ';\nwindow.BB_ITEMS = ' + JSON.stringify(items, null, 2) + ';\n';
const output = path.join(root, 'bb/images/monsters');
fs.mkdirSync(output, {recursive: true});
for (const [filename, bytes] of artwork) fs.writeFileSync(path.join(output, filename), bytes);
const manifestPath = path.join(root, 'bb/data/monsters.js');
fs.writeFileSync(manifestPath + '.tmp', manifest);
fs.renameSync(manifestPath + '.tmp', manifestPath);
for (const filename of fs.readdirSync(output)) {
  if (!assets.has(filename)) fs.unlinkSync(path.join(output, filename));
}
console.log(`Synced ${Object.values(profiles).reduce((n, group) => n + Object.keys(group).length, 0)} BB monster rows and ${assets.size} images.`);
